//! DDL Statement Parser
//!
//! Parses DDL statements (CREATE TABLE, ALTER TABLE) to extract TableDefinition objects.
//!
//! This parser is optimized for DDL statements generated by Graphica's SHACL-to-DDL
//! converter, but also handles hand-written DDL with common syntax variations.
//!
//! # Supported Dialects
//!
//! - DB2
//! - PostgreSQL
//! - Oracle
//!
//! # Design Philosophy
//!
//! This parser uses a combination of regex and manual parsing rather than a full
//! SQL parser dependency because:
//!
//! 1. We control the DDL generation format (from SHACL shapes)
//! 2. Predictable structure means faster, more reliable parsing
//! 3. No external parser dependency to manage
//! 4. Better error messages tailored to our use case
//! 5. Handles dialect-specific syntax variations we actually use

use crate::mapping::ddl::dialects::{ColumnDefinition, TableDefinition};
use anyhow::{anyhow, Context, Result};
use lazy_static::lazy_static;
use regex::Regex;
use std::collections::HashSet;
use tracing::{debug, warn};

/// Database dialect for parsing
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DbDialect {
    DB2,
    PostgreSQL,
    Oracle,
}

impl DbDialect {
    /// Parse from string
    pub fn from_str(s: &str) -> Result<Self> {
        match s.to_lowercase().as_str() {
            "db2" => Ok(DbDialect::DB2),
            "postgresql" | "postgres" | "pg" => Ok(DbDialect::PostgreSQL),
            "oracle" => Ok(DbDialect::Oracle),
            _ => Err(anyhow!("Unsupported database dialect: {}", s)),
        }
    }
}

/// Parsed DDL statement
#[derive(Debug, Clone)]
pub enum DdlStatement {
    CreateTable(TableDefinition),
    AlterTable {
        table_name: String,
        operation: AlterOperation,
    },
    CreateIndex {
        index_name: String,
        table_name: String,
    },
    DropTable {
        table_name: String,
    },
    Comment(String), // -- comment or /* comment */
    Unknown(String), // Unparseable statement
}

/// ALTER TABLE operations
#[derive(Debug, Clone)]
pub enum AlterOperation {
    AddColumn(ColumnDefinition),
    DropColumn(String),
    ModifyColumn(ColumnDefinition),
    AddConstraint(String),
    DropConstraint(String),
}

/// DDL Parser
pub struct DdlParser {
    dialect: DbDialect,
}

impl DdlParser {
    /// Create a new parser for the specified dialect
    pub fn new(dialect: DbDialect) -> Self {
        Self { dialect }
    }

    /// Parse multiple DDL statements (semicolon-separated)
    ///
    /// Handles:
    /// - Multiple statements separated by semicolons
    /// - SQL comments (-- and /* */)
    /// - Empty lines and whitespace
    /// - Statements spanning multiple lines
    ///
    /// Returns all successfully parsed CREATE TABLE statements as TableDefinitions.
    /// Logs warnings for unparseable statements but continues parsing.
    pub fn parse_ddl_script(&self, ddl_script: &str) -> Result<Vec<TableDefinition>> {
        let statements = self.split_statements(ddl_script);
        let mut tables = Vec::new();

        for (idx, stmt) in statements.iter().enumerate() {
            match self.parse_statement(stmt) {
                Ok(DdlStatement::CreateTable(table_def)) => {
                    debug!("Parsed CREATE TABLE: {}", table_def.name);
                    tables.push(table_def);
                }
                Ok(DdlStatement::Comment(_)) => {
                    // Ignore comments
                }
                Ok(other) => {
                    debug!(
                        "Skipping non-CREATE TABLE statement #{}: {:?}",
                        idx + 1,
                        other
                    );
                }
                Err(e) => {
                    warn!(
                        "Failed to parse statement #{}: {} - Statement: {}",
                        idx + 1,
                        e,
                        stmt
                    );
                    // Continue parsing other statements
                }
            }
        }

        Ok(tables)
    }

    /// Split DDL script into individual statements
    ///
    /// Handles:
    /// - Semicolon-separated statements
    /// - String literals with semicolons inside
    /// - Comments
    fn split_statements(&self, script: &str) -> Vec<String> {
        let mut statements = Vec::new();
        let mut current = String::new();
        let mut in_single_quote = false;
        let mut in_double_quote = false;
        let mut in_block_comment = false;
        let mut chars = script.chars().peekable();

        while let Some(ch) = chars.next() {
            // Handle block comments /* ... */
            if !in_single_quote && !in_double_quote {
                if ch == '/' && chars.peek() == Some(&'*') {
                    chars.next(); // consume '*'
                    in_block_comment = true;
                    continue;
                }
                if in_block_comment && ch == '*' && chars.peek() == Some(&'/') {
                    chars.next(); // consume '/'
                    in_block_comment = false;
                    continue;
                }
                if in_block_comment {
                    continue;
                }
            }

            // Handle line comments --
            if !in_single_quote && !in_double_quote && ch == '-' && chars.peek() == Some(&'-') {
                // Skip until end of line
                while let Some(&next_ch) = chars.peek() {
                    chars.next();
                    if next_ch == '\n' {
                        break;
                    }
                }
                continue;
            }

            // Track string literals
            if ch == '\'' && !in_double_quote {
                in_single_quote = !in_single_quote;
            } else if ch == '"' && !in_single_quote {
                in_double_quote = !in_double_quote;
            }

            // Statement separator
            if ch == ';' && !in_single_quote && !in_double_quote {
                let trimmed = current.trim();
                if !trimmed.is_empty() {
                    statements.push(trimmed.to_string());
                }
                current.clear();
            } else {
                current.push(ch);
            }
        }

        // Add final statement if present
        let trimmed = current.trim();
        if !trimmed.is_empty() {
            statements.push(trimmed.to_string());
        }

        statements
    }

    /// Parse a single DDL statement
    fn parse_statement(&self, stmt: &str) -> Result<DdlStatement> {
        let trimmed = stmt.trim();

        // Check for comments
        if trimmed.starts_with("--") || trimmed.starts_with("/*") {
            return Ok(DdlStatement::Comment(trimmed.to_string()));
        }

        // Detect statement type (case-insensitive)
        let upper = trimmed.to_uppercase();

        if upper.starts_with("CREATE TABLE") {
            self.parse_create_table(trimmed)
                .map(DdlStatement::CreateTable)
        } else if upper.starts_with("ALTER TABLE") {
            self.parse_alter_table(trimmed)
        } else if upper.starts_with("CREATE INDEX") || upper.starts_with("CREATE UNIQUE INDEX") {
            Ok(DdlStatement::CreateIndex {
                index_name: "parsed_index".to_string(),
                table_name: "unknown".to_string(),
            })
        } else if upper.starts_with("DROP TABLE") {
            Ok(DdlStatement::DropTable {
                table_name: "unknown".to_string(),
            })
        } else {
            Ok(DdlStatement::Unknown(trimmed.to_string()))
        }
    }

    /// Parse CREATE TABLE statement
    ///
    /// Handles:
    /// - Simple CREATE TABLE table_name (columns)
    /// - IF NOT EXISTS clause
    /// - PRIMARY KEY constraints (inline and out-of-line)
    /// - UNIQUE constraints
    /// - NOT NULL constraints
    /// - DEFAULT values
    /// - CHECK constraints
    /// - Dialect-specific syntax
    fn parse_create_table(&self, stmt: &str) -> Result<TableDefinition> {
        // Extract table name
        let table_name = self.extract_table_name(stmt)?;

        // Extract column definitions
        let column_section = self.extract_column_section(stmt)?;
        let (columns, primary_key) = self.parse_columns(&column_section)?;

        Ok(TableDefinition {
            name: table_name,
            columns,
            primary_key,
            foreign_keys: vec![],
            indexes: vec![],
            comment: None,
        })
    }

    /// Extract table name from CREATE TABLE statement
    fn extract_table_name(&self, stmt: &str) -> Result<String> {
        lazy_static! {
            // Matches: CREATE TABLE [IF NOT EXISTS] schema.table_name
            static ref RE: Regex = Regex::new(
                r"(?i)CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(?:(\w+)\.)?(\w+)"
            ).unwrap();
        }

        RE.captures(stmt)
            .and_then(|cap| {
                // Prefer table name with schema (group 2), fallback to just table name (group 1)
                cap.get(2)
                    .or_else(|| cap.get(1))
                    .map(|m| m.as_str().to_string())
            })
            .ok_or_else(|| anyhow!("Could not extract table name from: {}", stmt))
    }

    /// Extract column definitions section (between parentheses)
    fn extract_column_section(&self, stmt: &str) -> Result<String> {
        // Find first opening parenthesis
        let start = stmt
            .find('(')
            .ok_or_else(|| anyhow!("No opening parenthesis found in CREATE TABLE"))?;

        // Find matching closing parenthesis (handle nested parens)
        let mut depth = 0;
        let mut end = None;

        for (idx, ch) in stmt[start..].chars().enumerate() {
            match ch {
                '(' => depth += 1,
                ')' => {
                    depth -= 1;
                    if depth == 0 {
                        end = Some(start + idx);
                        break;
                    }
                }
                _ => {}
            }
        }

        let end = end.ok_or_else(|| anyhow!("No matching closing parenthesis found"))?;

        Ok(stmt[start + 1..end].trim().to_string())
    }

    /// Parse column definitions and extract primary key
    ///
    /// Handles:
    /// - Column definitions: name TYPE [NOT NULL] [PRIMARY KEY] [DEFAULT value] [CHECK (...)]
    /// - Out-of-line PRIMARY KEY (col1, col2, ...)
    /// - UNIQUE constraints
    /// - Commas separating columns
    /// - Whitespace variations
    fn parse_columns(&self, column_section: &str) -> Result<(Vec<ColumnDefinition>, Vec<String>)> {
        let mut columns = Vec::new();
        let mut primary_key_cols = Vec::new();
        let mut in_parens = 0;
        let mut current_col = String::new();

        // Split by commas (respecting parentheses)
        for ch in column_section.chars() {
            match ch {
                '(' => {
                    in_parens += 1;
                    current_col.push(ch);
                }
                ')' => {
                    in_parens -= 1;
                    current_col.push(ch);
                }
                ',' if in_parens == 0 => {
                    // Column separator
                    let col_str = current_col.trim();
                    if !col_str.is_empty() {
                        if let Some(pk_cols) = self.parse_out_of_line_primary_key(col_str) {
                            primary_key_cols = pk_cols;
                        } else if let Ok(col_def) = self.parse_column_definition(col_str) {
                            columns.push(col_def);
                        }
                    }
                    current_col.clear();
                }
                _ => current_col.push(ch),
            }
        }

        // Handle last column
        let col_str = current_col.trim();
        if !col_str.is_empty() {
            if let Some(pk_cols) = self.parse_out_of_line_primary_key(col_str) {
                primary_key_cols = pk_cols;
            } else if let Ok(col_def) = self.parse_column_definition(col_str) {
                columns.push(col_def);
            }
        }

        // If no out-of-line PK, check for inline PRIMARY KEY
        if primary_key_cols.is_empty() {
            primary_key_cols = columns
                .iter()
                .filter(|c| c.primary_key)
                .map(|c| c.name.clone())
                .collect();
        } else {
            // Mark columns as primary key
            for col in &mut columns {
                if primary_key_cols.contains(&col.name) {
                    col.primary_key = true;
                    col.nullable = false; // PRIMARY KEY implies NOT NULL
                }
            }
        }

        if columns.is_empty() {
            return Err(anyhow!("No columns found in CREATE TABLE statement"));
        }

        Ok((columns, primary_key_cols))
    }

    /// Try to parse out-of-line PRIMARY KEY constraint
    ///
    /// Example: "PRIMARY KEY (ID, NAME)"
    /// Returns: Some(vec!["ID", "NAME"])
    fn parse_out_of_line_primary_key(&self, constraint_str: &str) -> Option<Vec<String>> {
        let upper = constraint_str.trim().to_uppercase();

        if !upper.starts_with("PRIMARY KEY") && !upper.starts_with("CONSTRAINT") {
            return None;
        }

        // Extract column names from PRIMARY KEY (col1, col2, ...)
        lazy_static! {
            static ref RE: Regex = Regex::new(r"(?i)PRIMARY\s+KEY\s*\(([^)]+)\)").unwrap();
        }

        RE.captures(constraint_str)
            .map(|cap| cap[1].split(',').map(|s| s.trim().to_string()).collect())
    }

    /// Parse a single column definition
    ///
    /// Example: "EMAIL VARCHAR(255) NOT NULL UNIQUE"
    /// Returns: ColumnDefinition
    fn parse_column_definition(&self, col_str: &str) -> Result<ColumnDefinition> {
        let tokens: Vec<&str> = col_str.split_whitespace().collect();

        if tokens.is_empty() {
            return Err(anyhow!("Empty column definition"));
        }

        let name = tokens[0].to_string();

        // Extract SQL type (may have parens like VARCHAR(255))
        let sql_type = if tokens.len() > 1 {
            // Look for type with length/precision
            let mut type_str = tokens[1].to_string();

            // Handle types with parentheses: VARCHAR(255), DECIMAL(10,2)
            if tokens.len() > 2 && tokens[2].starts_with('(') {
                type_str.push_str(tokens[2]);
                if !tokens[2].ends_with(')') && tokens.len() > 3 {
                    type_str.push_str(tokens[3]);
                }
            } else if tokens[1].contains('(') {
                // Type and length together: VARCHAR(255)
                type_str = tokens[1].to_string();
            }

            type_str
        } else {
            return Err(anyhow!("Column definition missing type: {}", col_str));
        };

        // Parse constraints
        let upper = col_str.to_uppercase();
        let not_null = upper.contains("NOT NULL");
        let primary_key = upper.contains("PRIMARY KEY");
        let unique = upper.contains("UNIQUE");

        // Extract DEFAULT value
        let default_value = self.extract_default_value(col_str);

        // Extract CHECK constraint
        let check_constraint = self.extract_check_constraint(col_str);

        Ok(ColumnDefinition {
            name,
            sql_type,
            nullable: !not_null && !primary_key, // PK implies NOT NULL
            default_value,
            primary_key,
            unique,
            check_constraint,
            comment: None,
        })
    }

    /// Extract DEFAULT value from column definition
    ///
    /// Example: "STATUS VARCHAR(20) DEFAULT 'ACTIVE'" -> Some("'ACTIVE'")
    fn extract_default_value(&self, col_str: &str) -> Option<String> {
        lazy_static! {
            static ref RE: Regex = Regex::new(r"(?i)DEFAULT\s+('(?:[^']|'')*'|\S+)").unwrap();
        }

        RE.captures(col_str)
            .and_then(|cap| cap.get(1).map(|m| m.as_str().to_string()))
    }

    /// Extract CHECK constraint from column definition
    ///
    /// Example: "AGE INTEGER CHECK (AGE >= 18)" -> Some("AGE >= 18")
    fn extract_check_constraint(&self, col_str: &str) -> Option<String> {
        lazy_static! {
            static ref RE: Regex = Regex::new(r"(?i)CHECK\s*\(([^)]+)\)").unwrap();
        }

        RE.captures(col_str)
            .and_then(|cap| cap.get(1).map(|m| m.as_str().trim().to_string()))
    }

    /// Parse ALTER TABLE statement (basic support)
    fn parse_alter_table(&self, stmt: &str) -> Result<DdlStatement> {
        // Basic table name extraction
        lazy_static! {
            static ref RE: Regex = Regex::new(r"(?i)ALTER\s+TABLE\s+(\w+)").unwrap();
        }

        let table_name = RE
            .captures(stmt)
            .and_then(|cap| cap.get(1).map(|m| m.as_str().to_string()))
            .ok_or_else(|| anyhow!("Could not extract table name from ALTER TABLE"))?;

        // For now, return a placeholder operation
        // Full ALTER TABLE parsing can be added later if needed
        Ok(DdlStatement::AlterTable {
            table_name,
            operation: AlterOperation::AddConstraint("unknown".to_string()),
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_simple_create_table() {
        let parser = DdlParser::new(DbDialect::PostgreSQL);
        let ddl = "CREATE TABLE customers (id INTEGER PRIMARY KEY, name VARCHAR(255) NOT NULL)";

        let tables = parser.parse_ddl_script(ddl).unwrap();
        assert_eq!(tables.len(), 1);

        let table = &tables[0];
        assert_eq!(table.name, "customers");
        assert_eq!(table.columns.len(), 2);
        assert_eq!(table.primary_key, vec!["id"]);

        let id_col = &table.columns[0];
        assert_eq!(id_col.name, "id");
        assert_eq!(id_col.sql_type, "INTEGER");
        assert!(id_col.primary_key);
        assert!(!id_col.nullable);

        let name_col = &table.columns[1];
        assert_eq!(name_col.name, "name");
        assert_eq!(name_col.sql_type, "VARCHAR(255)");
        assert!(!name_col.nullable);
    }

    #[test]
    fn test_parse_multiline_create_table() {
        let parser = DdlParser::new(DbDialect::DB2);
        let ddl = r#"
            CREATE TABLE orders (
                order_id INTEGER NOT NULL,
                customer_id INTEGER,
                order_date DATE NOT NULL,
                total_amount DECIMAL(10,2),
                PRIMARY KEY (order_id)
            )
        "#;

        let tables = parser.parse_ddl_script(ddl).unwrap();
        assert_eq!(tables.len(), 1);

        let table = &tables[0];
        assert_eq!(table.name, "orders");
        assert_eq!(table.columns.len(), 4);
        assert_eq!(table.primary_key, vec!["order_id"]);

        // Verify primary key is marked on column
        let pk_col = table.columns.iter().find(|c| c.name == "order_id").unwrap();
        assert!(pk_col.primary_key);
    }

    #[test]
    fn test_parse_with_default_values() {
        let parser = DdlParser::new(DbDialect::PostgreSQL);
        let ddl = "CREATE TABLE users (
            id SERIAL PRIMARY KEY,
            status VARCHAR(20) DEFAULT 'ACTIVE',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )";

        let tables = parser.parse_ddl_script(ddl).unwrap();
        let table = &tables[0];

        let status_col = table.columns.iter().find(|c| c.name == "status").unwrap();
        assert_eq!(status_col.default_value, Some("'ACTIVE'".to_string()));

        let created_col = table
            .columns
            .iter()
            .find(|c| c.name == "created_at")
            .unwrap();
        assert_eq!(
            created_col.default_value,
            Some("CURRENT_TIMESTAMP".to_string())
        );
    }

    #[test]
    fn test_parse_with_check_constraint() {
        let parser = DdlParser::new(DbDialect::PostgreSQL);
        let ddl = "CREATE TABLE employees (
            id INTEGER PRIMARY KEY,
            age INTEGER CHECK (age >= 18),
            salary DECIMAL(10,2) CHECK (salary > 0)
        )";

        let tables = parser.parse_ddl_script(ddl).unwrap();
        let table = &tables[0];

        let age_col = table.columns.iter().find(|c| c.name == "age").unwrap();
        assert_eq!(age_col.check_constraint, Some("age >= 18".to_string()));

        let salary_col = table.columns.iter().find(|c| c.name == "salary").unwrap();
        assert_eq!(salary_col.check_constraint, Some("salary > 0".to_string()));
    }

    #[test]
    fn test_parse_multiple_statements() {
        let parser = DdlParser::new(DbDialect::PostgreSQL);
        let ddl = "
            CREATE TABLE table1 (id INTEGER PRIMARY KEY);
            CREATE TABLE table2 (id INTEGER PRIMARY KEY, name VARCHAR(100));
            CREATE INDEX idx_name ON table2(name);
        ";

        let tables = parser.parse_ddl_script(ddl).unwrap();
        assert_eq!(tables.len(), 2);
        assert_eq!(tables[0].name, "table1");
        assert_eq!(tables[1].name, "table2");
    }

    #[test]
    fn test_parse_with_comments() {
        let parser = DdlParser::new(DbDialect::PostgreSQL);
        let ddl = "
            -- This is a customer table
            CREATE TABLE customers (
                id INTEGER PRIMARY KEY, -- Primary key
                name VARCHAR(255) /* Customer name */
            );
            /* Multi-line comment
               spanning multiple lines */
            CREATE TABLE orders (id INTEGER PRIMARY KEY);
        ";

        let tables = parser.parse_ddl_script(ddl).unwrap();
        assert_eq!(tables.len(), 2);
    }

    #[test]
    fn test_parse_if_not_exists() {
        let parser = DdlParser::new(DbDialect::PostgreSQL);
        let ddl = "CREATE TABLE IF NOT EXISTS customers (id INTEGER PRIMARY KEY)";

        let tables = parser.parse_ddl_script(ddl).unwrap();
        assert_eq!(tables.len(), 1);
        assert_eq!(tables[0].name, "customers");
    }

    #[test]
    fn test_sad_path_empty_ddl() {
        let parser = DdlParser::new(DbDialect::PostgreSQL);
        let ddl = "";

        let tables = parser.parse_ddl_script(ddl).unwrap();
        assert_eq!(tables.len(), 0);
    }

    #[test]
    fn test_sad_path_only_comments() {
        let parser = DdlParser::new(DbDialect::PostgreSQL);
        let ddl = "-- Just a comment\n/* Another comment */";

        let tables = parser.parse_ddl_script(ddl).unwrap();
        assert_eq!(tables.len(), 0);
    }

    #[test]
    fn test_sad_path_malformed_ddl() {
        let parser = DdlParser::new(DbDialect::PostgreSQL);
        let ddl = "CREATE TABLE (id INTEGER"; // Missing table name and closing paren

        let tables = parser.parse_ddl_script(ddl).unwrap();
        // Should return empty vec and log warning, not crash
        assert_eq!(tables.len(), 0);
    }

    #[test]
    fn test_sad_path_semicolon_in_string() {
        let parser = DdlParser::new(DbDialect::PostgreSQL);
        let ddl = "CREATE TABLE test (
            description VARCHAR(255) DEFAULT 'Value with ; semicolon',
            id INTEGER PRIMARY KEY
        )";

        let tables = parser.parse_ddl_script(ddl).unwrap();
        assert_eq!(tables.len(), 1);
        assert_eq!(tables[0].columns.len(), 2);
    }

    #[test]
    fn test_sad_path_nested_parentheses() {
        let parser = DdlParser::new(DbDialect::PostgreSQL);
        let ddl = "CREATE TABLE test (
            data VARCHAR(100) CHECK (LENGTH(TRIM(data)) > 0),
            id INTEGER PRIMARY KEY
        )";

        let tables = parser.parse_ddl_script(ddl).unwrap();
        assert_eq!(tables.len(), 1);
        assert_eq!(tables[0].columns.len(), 2);

        let data_col = &tables[0].columns.iter().find(|c| c.name == "data").unwrap();
        assert!(data_col.check_constraint.is_some());
    }

    #[test]
    fn test_extract_table_name_with_schema() {
        let parser = DdlParser::new(DbDialect::DB2);
        let ddl = "CREATE TABLE myschema.customers (id INTEGER)";

        let tables = parser.parse_ddl_script(ddl).unwrap();
        // For now we might get just "customers" or "myschema.customers"
        // depending on implementation - verify it doesn't crash
        assert_eq!(tables.len(), 1);
    }

    #[test]
    fn test_dialect_from_str() {
        assert!(matches!(
            DbDialect::from_str("db2").unwrap(),
            DbDialect::DB2
        ));
        assert!(matches!(
            DbDialect::from_str("DB2").unwrap(),
            DbDialect::DB2
        ));
        assert!(matches!(
            DbDialect::from_str("postgresql").unwrap(),
            DbDialect::PostgreSQL
        ));
        assert!(matches!(
            DbDialect::from_str("postgres").unwrap(),
            DbDialect::PostgreSQL
        ));
        assert!(matches!(
            DbDialect::from_str("pg").unwrap(),
            DbDialect::PostgreSQL
        ));
        assert!(matches!(
            DbDialect::from_str("oracle").unwrap(),
            DbDialect::Oracle
        ));

        assert!(DbDialect::from_str("mysql").is_err());
        assert!(DbDialect::from_str("invalid").is_err());
    }
}
