// RDF Converters - Domain Types → RDF Triples
//
// This module provides converters to transform Graphica domain types
// into RDF triples for storage in the governance brain.

use super::ontology::{uris, GRAPHICA_NS, ML_NS, PROV_NS};
use anyhow::Result;
use graphica_core::core::lineage::LineageEvent;
use uuid::Uuid;

/// Trait for converting domain types to RDF triples
pub trait ToRdfTriples {
    /// Convert to RDF triples (subject, predicate, object)
    fn to_rdf_triples(&self) -> Result<Vec<(String, String, String)>>;
}

/// RDF triple helper
pub struct Triple {
    pub subject: String,
    pub predicate: String,
    pub object: String,
}

impl Triple {
    pub fn new(
        subject: impl Into<String>,
        predicate: impl Into<String>,
        object: impl Into<String>,
    ) -> Self {
        Self {
            subject: subject.into(),
            predicate: predicate.into(),
            object: object.into(),
        }
    }

    pub fn to_tuple(self) -> (String, String, String) {
        (self.subject, self.predicate, self.object)
    }
}

/// Convert LineageEvent to RDF triples (delegates to LineageConverter for comprehensive conversion)
impl ToRdfTriples for LineageEvent {
    fn to_rdf_triples(&self) -> Result<Vec<(String, String, String)>> {
        // Use the comprehensive LineageConverter implementation
        // which includes CDC positions, transform details, and model metrics
        use super::lineage_converter::LineageConverter;
        LineageConverter::to_rdf_triples_detailed(self)
    }
}

/// Model prediction to RDF triples
pub struct ModelPrediction {
    pub entity_id: String,
    pub model_id: String,
    pub model_version: String,
    pub attribute_name: String,
    pub value: String,
    pub confidence: f64,
    pub timestamp: i64,
}

impl ToRdfTriples for ModelPrediction {
    fn to_rdf_triples(&self) -> Result<Vec<(String, String, String)>> {
        let mut triples = Vec::new();

        let entity_uri = uris::entity(&self.entity_id);
        let attr_uri = uris::attribute(&Uuid::new_v4().to_string());
        let model_uri = uris::model(&self.model_id);

        // Entity has derived attribute
        triples.push(
            Triple::new(
                &entity_uri,
                format!("{}hasDerivedAttribute", GRAPHICA_NS),
                &attr_uri,
            )
            .to_tuple(),
        );

        // Attribute details
        triples.push(
            Triple::new(
                &attr_uri,
                format!("{}type", PROV_NS),
                format!("{}DerivedAttribute", GRAPHICA_NS),
            )
            .to_tuple(),
        );

        triples.push(
            Triple::new(
                &attr_uri,
                format!("{}attributeName", GRAPHICA_NS),
                &self.attribute_name,
            )
            .to_tuple(),
        );

        triples
            .push(Triple::new(&attr_uri, format!("{}value", GRAPHICA_NS), &self.value).to_tuple());

        triples.push(
            Triple::new(
                &attr_uri,
                format!("{}confidence", GRAPHICA_NS),
                self.confidence.to_string(),
            )
            .to_tuple(),
        );

        // Provenance: generated by model
        triples.push(
            Triple::new(&attr_uri, format!("{}wasGeneratedBy", PROV_NS), &model_uri).to_tuple(),
        );

        triples.push(
            Triple::new(
                &attr_uri,
                format!("{}generatedAtTime", PROV_NS),
                self.timestamp.to_string(),
            )
            .to_tuple(),
        );

        // Model metadata
        triples.push(
            Triple::new(&model_uri, format!("{}version", ML_NS), &self.model_version).to_tuple(),
        );

        Ok(triples)
    }
}

/// Fusion operation to RDF triples
pub struct FusionOperation {
    pub fusion_id: String,
    pub merged_entity_id: String,
    pub source_entity_ids: Vec<String>,
    pub rule_id: String,
    pub confidence: f64,
    pub timestamp: i64,
}

impl ToRdfTriples for FusionOperation {
    fn to_rdf_triples(&self) -> Result<Vec<(String, String, String)>> {
        let mut triples = Vec::new();

        let fusion_uri = uris::fusion(&self.fusion_id);
        let merged_uri = uris::entity(&self.merged_entity_id);

        // Fusion operation as PROV Activity
        triples.push(
            Triple::new(
                &fusion_uri,
                format!("{}type", PROV_NS),
                format!("{}FusionOperation", GRAPHICA_NS),
            )
            .to_tuple(),
        );

        triples.push(
            Triple::new(
                &fusion_uri,
                format!("{}mergedEntity", GRAPHICA_NS),
                &merged_uri,
            )
            .to_tuple(),
        );

        // Source entities
        for source_id in &self.source_entity_ids {
            let source_uri = uris::entity(source_id);

            triples.push(
                Triple::new(
                    &fusion_uri,
                    format!("{}sourceEntity", GRAPHICA_NS),
                    &source_uri,
                )
                .to_tuple(),
            );
        }

        // Fusion metadata
        triples.push(
            Triple::new(
                &fusion_uri,
                format!("{}fusionRule", GRAPHICA_NS),
                &self.rule_id,
            )
            .to_tuple(),
        );

        triples.push(
            Triple::new(
                &fusion_uri,
                format!("{}fusionConfidence", GRAPHICA_NS),
                self.confidence.to_string(),
            )
            .to_tuple(),
        );

        triples.push(
            Triple::new(
                &fusion_uri,
                format!("{}atTime", PROV_NS),
                self.timestamp.to_string(),
            )
            .to_tuple(),
        );

        Ok(triples)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::Utc;
    use graphica_core::core::lineage::{DataRef, TransformRef};
    use std::collections::HashMap;

    #[test]
    fn test_lineage_event_to_triples() {
        let now = Utc::now();
        let event = LineageEvent {
            id: Uuid::new_v4(),
            dataset: "customers".to_string(),
            record_id: "cust_456".to_string(),
            source_refs: vec![DataRef {
                system: "kafka".to_string(),
                path: "topic/customers".to_string(),
                version: None,
                extracted_at: now,
                cdc_position: None,
            }],
            transforms: vec![TransformRef {
                id: Uuid::new_v4(),
                transform_type: "standardize".to_string(),
                rule_id: "std_001".to_string(),
                version: "1.0.0".to_string(),
                parameters: HashMap::new(),
                applied_at: now,
                fields_modified: vec![],
            }],
            model_refs: vec![],
            output_ref: DataRef {
                system: "output".to_string(),
                path: "processed/customers".to_string(),
                version: None,
                extracted_at: now,
                cdc_position: None,
            },
            ts: now,
            run_id: "run_789".to_string(),
            tenant_id: "tenant_001".to_string(),
            correlation_id: None,
            metadata: HashMap::new(),
        };

        let triples = event.to_rdf_triples().unwrap();

        // Check some key triples exist
        assert!(triples.iter().any(|(_, p, _)| { p.contains("type") }));

        assert!(triples
            .iter()
            .any(|(_, p, o)| { p.contains("dataset") && o == "customers" }));
    }

    #[test]
    fn test_model_prediction_to_triples() {
        let prediction = ModelPrediction {
            entity_id: "cust_123".to_string(),
            model_id: "mdl_456".to_string(),
            model_version: "1.2.0".to_string(),
            attribute_name: "gender".to_string(),
            value: "female".to_string(),
            confidence: 0.85,
            timestamp: 1729000000,
        };

        let triples = prediction.to_rdf_triples().unwrap();

        assert!(triples
            .iter()
            .any(|(_, p, _)| p.contains("hasDerivedAttribute")));
        assert!(triples
            .iter()
            .any(|(_, p, o)| p.contains("confidence") && o == "0.85"));
    }

    #[test]
    fn test_fusion_operation_to_triples() {
        let fusion = FusionOperation {
            fusion_id: "fus_123".to_string(),
            merged_entity_id: "cust_111".to_string(),
            source_entity_ids: vec!["cust_222".to_string(), "cust_333".to_string()],
            rule_id: "email_exact_match".to_string(),
            confidence: 0.95,
            timestamp: 1729000000,
        };

        let triples = fusion.to_rdf_triples().unwrap();

        assert!(triples
            .iter()
            .any(|(_, _, o)| o.contains("FusionOperation")));
        assert!(triples.iter().any(|(_, p, _)| p.contains("mergedEntity")));
        assert_eq!(
            triples
                .iter()
                .filter(|(_, p, _)| p.contains("sourceEntity"))
                .count(),
            2
        );
    }
}
