apiVersion: v1
kind: Secret
metadata:
  name: graphica-pull
  annotations:
    "helm.sh/hook-weight": "-5"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}