apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.graphica.serviceAccountName }}
---
{{ if .Values.openshiftMode.enabled }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: arcxa-nonroot-v2
subjects:
  - kind: ServiceAccount
    name: {{ .Values.graphica.serviceAccountName }}
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:nonroot-v2
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: arcxa-anyuid
subjects:
  - kind: ServiceAccount
    name: {{ .Values.graphica.serviceAccountName }}
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:anyuid
  apiGroup: rbac.authorization.k8s.io
{{end}}
