//! OpenAPI documentation for Systems-of-Systems (SoS) Validation API
//!
//! This module aggregates all SoS validation endpoints into a single OpenAPI specification.

use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    paths(
        // System Management
        crate::api::sos_validation::handlers::register_system,
        crate::api::sos_validation::handlers::list_systems,
        crate::api::sos_validation::handlers::get_system,
        crate::api::sos_validation::handlers::update_system,
        crate::api::sos_validation::handlers::delete_system,
        crate::api::sos_validation::handlers::list_system_interfaces,
        // Interface Definition
        crate::api::sos_validation::handlers::register_interface,
        crate::api::sos_validation::handlers::list_interfaces,
        crate::api::sos_validation::handlers::get_interface,
        crate::api::sos_validation::handlers::update_interface,
        crate::api::sos_validation::handlers::delete_interface,
        crate::api::sos_validation::handlers::validate_interface_schema,
        // Data Contracts
        crate::api::sos_validation::handlers::create_contract,
        crate::api::sos_validation::handlers::list_contracts,
        crate::api::sos_validation::handlers::lookup_contract,
        crate::api::sos_validation::handlers::get_contract_signing_key_status,
        crate::api::sos_validation::handlers::rotate_contract_signing_key,
        crate::api::sos_validation::handlers::get_contract,
        crate::api::sos_validation::handlers::update_contract,
        crate::api::sos_validation::handlers::delete_contract,
        crate::api::sos_validation::handlers::list_contract_signatures,
        crate::api::sos_validation::handlers::create_contract_approval_request,
        crate::api::sos_validation::handlers::list_contract_approval_requests,
        crate::api::sos_validation::handlers::get_contract_approval_request,
        crate::api::sos_validation::handlers::add_contract_approval_evidence,
        crate::api::sos_validation::handlers::approve_contract_approval_request,
        crate::api::sos_validation::handlers::reject_contract_approval_request,
        crate::api::sos_validation::handlers::approve_contract,
        crate::api::sos_validation::handlers::sign_contract,
        // Validation
        crate::api::sos_validation::handlers::validate,
        crate::api::sos_validation::handlers::validate_dry_run,
        crate::api::sos_validation::handlers::create_policy,
        crate::api::sos_validation::handlers::list_policies,
        crate::api::sos_validation::handlers::get_policy_signing_key_status,
        crate::api::sos_validation::handlers::rotate_policy_signing_key,
        crate::api::sos_validation::handlers::get_policy,
        crate::api::sos_validation::handlers::update_policy,
        crate::api::sos_validation::handlers::delete_policy,
        crate::api::sos_validation::handlers::list_policy_attestations,
        crate::api::sos_validation::handlers::create_policy_approval_request,
        crate::api::sos_validation::handlers::list_policy_approval_requests,
        crate::api::sos_validation::handlers::get_policy_approval_request,
        crate::api::sos_validation::handlers::add_policy_approval_evidence,
        crate::api::sos_validation::handlers::approve_policy_approval_request,
        crate::api::sos_validation::handlers::reject_policy_approval_request,
        crate::api::sos_validation::handlers::approve_policy,
        crate::api::sos_validation::handlers::reject_policy,
        crate::api::sos_validation::handlers::validate_policy,
        crate::api::sos_validation::handlers::validate_policy_dry_run,
        crate::api::sos_validation::handlers::get_validation_report,
        crate::api::sos_validation::handlers::get_validation_history,
        crate::api::sos_validation::handlers::get_validation_lineage,
        // Analytics
        crate::api::sos_validation::handlers::get_compatibility_matrix,
        crate::api::sos_validation::handlers::get_dependency_graph,
        crate::api::sos_validation::handlers::what_if_analysis,
        crate::api::sos_validation::handlers::reconcile_sos_runtime,
    ),
    components(
        schemas(
            // System Management types
            crate::api::sos_validation::types::RegisterSystemRequest,
            crate::api::sos_validation::types::UpdateSystemRequest,
            crate::api::sos_validation::types::ListSystemsQuery,
            crate::api::sos_validation::types::SystemResponse,
            crate::api::sos_validation::types::ListSystemsResponse,
            // Interface Definition types
            crate::api::sos_validation::types::SystemInterface,
            crate::api::sos_validation::types::RegisterInterfaceRequest,
            crate::api::sos_validation::types::UpdateInterfaceRequest,
            crate::api::sos_validation::types::InterfaceResponse,
            // Data Contract types
            crate::api::sos_validation::types::SlaMetric,
            crate::api::sos_validation::types::CreateDataContractRequest,
            crate::api::sos_validation::types::UpdateDataContractRequest,
            crate::api::sos_validation::types::ContractLookupQuery,
            crate::api::sos_validation::types::DataContractResponse,
            crate::api::sos_validation::types::SosContractSignatureResponse,
            crate::api::sos_validation::types::ListContractSignaturesQuery,
            crate::api::sos_validation::types::ListContractSignaturesResponse,
            crate::api::sos_validation::types::SosContractSigningKeyStatusResponse,
            crate::api::sos_validation::types::RotateSosContractSigningKeyRequest,
            crate::api::sos_validation::types::RotateSosContractSigningKeyResponse,
            crate::api::sos_validation::types::CreateSosContractApprovalRequest,
            crate::api::sos_validation::types::AddSosContractApprovalEvidenceRequest,
            crate::api::sos_validation::types::ApproveSosContractApprovalRequest,
            crate::api::sos_validation::types::RejectSosContractApprovalRequest,
            crate::api::sos_validation::types::ListContractApprovalRequestsQuery,
            crate::api::sos_validation::types::SosContractApprovalEvidenceResponse,
            crate::api::sos_validation::types::SosContractApprovalRequestResponse,
            crate::api::sos_validation::types::ListContractApprovalRequestsResponse,
            // Validation types
            crate::api::sos_validation::types::ValidateRequest,
            crate::api::sos_validation::types::CheckResult,
            crate::api::sos_validation::types::ValidationResponse,
            crate::api::sos_validation::types::ValidationReportResponse,
            crate::api::sos_validation::types::ValidationChangeSummaryResponse,
            crate::api::sos_validation::types::ValidationHistoryQuery,
            crate::api::sos_validation::types::ValidationHistoryResponse,
            crate::api::sos_validation::types::ValidationLineageQuery,
            crate::api::sos_validation::types::ValidationLineageEdge,
            crate::api::sos_validation::types::ValidationLineageResponse,
            crate::api::sos_validation::types::CreateSosPolicyRequest,
            crate::api::sos_validation::types::UpdateSosPolicyRequest,
            crate::api::sos_validation::types::CreateSosPolicyApprovalRequest,
            crate::api::sos_validation::types::AddSosPolicyApprovalEvidenceRequest,
            crate::api::sos_validation::types::ApproveSosPolicyApprovalRequest,
            crate::api::sos_validation::types::RejectSosPolicyApprovalRequest,
            crate::api::sos_validation::types::ApproveSosPolicyRequest,
            crate::api::sos_validation::types::RejectSosPolicyRequest,
            crate::api::sos_validation::types::ListPolicyApprovalRequestsQuery,
            crate::api::sos_validation::types::SosPolicyApprovalEvidenceResponse,
            crate::api::sos_validation::types::SosPolicyApprovalRequestResponse,
            crate::api::sos_validation::types::ListPolicyApprovalRequestsResponse,
            crate::api::sos_validation::types::ListPolicyAttestationsQuery,
            crate::api::sos_validation::types::SosPolicySigningKeyStatusResponse,
            crate::api::sos_validation::types::RotateSosPolicySigningKeyRequest,
            crate::api::sos_validation::types::RotateSosPolicySigningKeyResponse,
            crate::api::sos_validation::types::ListPoliciesQuery,
            crate::api::sos_validation::types::SosPolicyResponse,
            crate::api::sos_validation::types::SosPolicyAttestationResponse,
            crate::api::sos_validation::types::ListPolicyAttestationsResponse,
            crate::api::sos_validation::types::ListPoliciesResponse,
            crate::api::sos_validation::types::EvaluatePolicyRequest,
            // Analytics types
            crate::api::sos_validation::types::CompatibilityMatrixQuery,
            crate::api::sos_validation::types::DependencyGraphQuery,
            crate::api::sos_validation::types::CompatibilityScore,
            crate::api::sos_validation::types::CompatibilityDetail,
            crate::api::sos_validation::types::CompatibilityMatrixMetadata,
            crate::api::sos_validation::types::CompatibilityMatrixResponse,
            crate::api::sos_validation::types::DependencyGraphNode,
            crate::api::sos_validation::types::DependencyGraphEdge,
            crate::api::sos_validation::types::DependencyGraphMetadata,
            crate::api::sos_validation::types::DependencyGraphResponse,
            crate::api::sos_validation::types::WhatIfRequest,
            crate::api::sos_validation::types::WhatIfAnalysisMetadata,
            crate::api::sos_validation::types::WhatIfResponse,
            crate::api::sos_validation::types::ReconcileSosRequest,
            crate::api::sos_validation::types::ReconcileSosResponse,
            // Error types
            crate::api::sos_validation::types::SosErrorResponse,
        )
    ),
    tags(
        (name = "SoS - System Management", description = "Register and manage systems in the SoS catalog with capabilities and deployment information"),
        (name = "SoS - Interface Definition", description = "Define system interfaces with schemas, coordinate systems, and unit specifications"),
        (name = "SoS - Data Contracts", description = "Create and manage data contracts between interfaces with SLA requirements"),
        (name = "SoS - Validation", description = "Execute cross-system validation for compatibility, policies, and SLA compliance"),
        (name = "SoS - Analytics", description = "Analyze compatibility matrices, dependency graphs, and what-if scenarios"),
    ),
    info(
        title = "ARCXA Systems-of-Systems Validation API",
        version = "1.0.0",
        description = "REST API for validating compatibility and integration between systems in a Systems-of-Systems architecture. Supports system registration, interface definition, data contracts, cross-system validation (schemas, units, coordinate systems, SLAs), and analytics.",
        contact(
            name = "ARCXA Team",
            email = "avinam@equitus.us"
        )
    ),
    servers(
        (url = "http://localhost:8080", description = "Development server"),
        (url = "https://api.graphica.io", description = "Production server")
    )
)]
pub struct SosValidationApiDoc;
