{{- if .Values.graphica.coordinator.enabled -}}
kind: Secret
apiVersion: v1
metadata:
  name: arcxa-initial-admin
  namespace: {{ .Release.namespace }}
data:
  JWT_SECRET: R3JAcGhBZG0xblBAc3N3MHJk # Gr@phAdm1nP@ssw0rd
type: Opaque
{{- end }}
