{{- if .Values.graphica.coordinator.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: arcxa-coordinator
  namespace: {{ .Release.namespace }}
spec:
  ports:
  - port: 8080
    name: http
  - port: 9090
    name: grpc
  clusterIP: None
  selector:
    app: graphica
    component: coordinator
  {{- end }}
