{{- if .Values.graphica.frontend.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphica-frontend
  namespace: graphica
spec:
  replicas: {{ .Values.graphica.frontend.replicas }}
  selector:
    matchLabels:
      app: graphica
      component: frontend
  template:
    metadata:
      labels:
        app: graphica
        component: frontend
    spec:
      serviceAccountName: {{ .Values.graphica.serviceAccountName }}
      imagePullSecrets:
      - name: graphica-pull
      containers:
      - name: graphica-frontend
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        image: {{ .Values.graphica.frontend.imageTag }}
        env:
        - name: VITE_API_URL
          value: 'http://graphica-coordinator:8080/api/v1'
        securityContext:
          runAsUser: 1000
{{- end }}