{{- if .Values.graphica.frontend.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: arcxa-frontend
  namespace: {{ .Release.namespace }}
spec:
  ports:
  - port: 8080
    name: http
  clusterIP: None
  selector:
    app: graphica
    component: frontend
{{- end }}
