-- ============================================================================
-- Graphica DB2 Test Schema Initialization
-- ============================================================================
-- Creates test tables for CSV-to-DB2 ETL pipeline validation
-- Tests both INSERT and MERGE modes with various data types
-- ============================================================================

CONNECT TO GRAPHICA;

-- ============================================================================
-- CUSTOMERS Table - For testing MERGE/UPSERT with primary keys
-- ============================================================================
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID INTEGER NOT NULL PRIMARY KEY,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PHONE VARCHAR(20),
    DATE_OF_BIRTH DATE,
    REGISTRATION_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LOYALTY_POINTS INTEGER DEFAULT 0,
    IS_ACTIVE SMALLINT DEFAULT 1,
    LAST_PURCHASE_DATE DATE,
    TOTAL_SPENT DECIMAL(12, 2) DEFAULT 0.00,
    CUSTOMER_SEGMENT VARCHAR(50),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_CUSTOMERS_EMAIL ON CUSTOMERS(EMAIL);
CREATE INDEX IDX_CUSTOMERS_SEGMENT ON CUSTOMERS(CUSTOMER_SEGMENT);
CREATE INDEX IDX_CUSTOMERS_ACTIVE ON CUSTOMERS(IS_ACTIVE);

COMMENT ON TABLE CUSTOMERS IS 'Customer master data - test table for MERGE/UPSERT operations';
COMMENT ON COLUMN CUSTOMERS.CUSTOMER_ID IS 'Primary key - used in MERGE ON clause';
COMMENT ON COLUMN CUSTOMERS.EMAIL IS 'Unique email address';
COMMENT ON COLUMN CUSTOMERS.IS_ACTIVE IS '1=active, 0=inactive';

-- ============================================================================
-- PRODUCTS Table - For testing composite primary keys
-- ============================================================================
CREATE TABLE PRODUCTS (
    PRODUCT_ID INTEGER NOT NULL,
    VARIANT_ID INTEGER NOT NULL,
    PRODUCT_NAME VARCHAR(255) NOT NULL,
    CATEGORY VARCHAR(100),
    SUBCATEGORY VARCHAR(100),
    UNIT_PRICE DECIMAL(10, 2) NOT NULL,
    COST_PRICE DECIMAL(10, 2),
    IN_STOCK INTEGER DEFAULT 0,
    REORDER_LEVEL INTEGER DEFAULT 10,
    SUPPLIER_ID INTEGER,
    PRODUCT_STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (PRODUCT_ID, VARIANT_ID)
);

CREATE INDEX IDX_PRODUCTS_CATEGORY ON PRODUCTS(CATEGORY, SUBCATEGORY);
CREATE INDEX IDX_PRODUCTS_SUPPLIER ON PRODUCTS(SUPPLIER_ID);
CREATE INDEX IDX_PRODUCTS_STATUS ON PRODUCTS(PRODUCT_STATUS);

COMMENT ON TABLE PRODUCTS IS 'Product catalog - test table for composite primary key MERGE';
COMMENT ON COLUMN PRODUCTS.PRODUCT_ID IS 'Product ID - part of composite PK';
COMMENT ON COLUMN PRODUCTS.VARIANT_ID IS 'Variant ID (size/color) - part of composite PK';

-- ============================================================================
-- ORDERS Table - For testing INSERT-only mode (append-only)
-- ============================================================================
CREATE TABLE ORDERS (
    ORDER_ID BIGINT NOT NULL PRIMARY KEY,
    CUSTOMER_ID INTEGER NOT NULL,
    ORDER_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ORDER_STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    SHIPPING_ADDRESS VARCHAR(500),
    BILLING_ADDRESS VARCHAR(500),
    SUBTOTAL DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    TAX_AMOUNT DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    SHIPPING_COST DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    TOTAL_AMOUNT DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    PAYMENT_METHOD VARCHAR(50),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_ORDERS_CUSTOMER ON ORDERS(CUSTOMER_ID);
CREATE INDEX IDX_ORDERS_DATE ON ORDERS(ORDER_DATE);
CREATE INDEX IDX_ORDERS_STATUS ON ORDERS(ORDER_STATUS);

COMMENT ON TABLE ORDERS IS 'Order transactions - test table for INSERT-only (append) mode';
COMMENT ON COLUMN ORDERS.ORDER_ID IS 'Primary key - unique order identifier';

-- ============================================================================
-- ORDER_ITEMS Table - For testing large batch inserts
-- ============================================================================
CREATE TABLE ORDER_ITEMS (
    ORDER_ITEM_ID BIGINT NOT NULL PRIMARY KEY,
    ORDER_ID BIGINT NOT NULL,
    PRODUCT_ID INTEGER NOT NULL,
    VARIANT_ID INTEGER NOT NULL,
    QUANTITY INTEGER NOT NULL DEFAULT 1,
    UNIT_PRICE DECIMAL(10, 2) NOT NULL,
    DISCOUNT_PERCENT DECIMAL(5, 2) DEFAULT 0.00,
    LINE_TOTAL DECIMAL(12, 2) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (PRODUCT_ID, VARIANT_ID) REFERENCES PRODUCTS(PRODUCT_ID, VARIANT_ID)
);

CREATE INDEX IDX_ORDER_ITEMS_ORDER ON ORDER_ITEMS(ORDER_ID);
CREATE INDEX IDX_ORDER_ITEMS_PRODUCT ON ORDER_ITEMS(PRODUCT_ID, VARIANT_ID);

COMMENT ON TABLE ORDER_ITEMS IS 'Order line items - test table for bulk INSERT performance';

-- ============================================================================
-- CUSTOMER_EVENTS Table - For testing high-volume streaming inserts
-- ============================================================================
CREATE TABLE CUSTOMER_EVENTS (
    EVENT_ID BIGINT NOT NULL PRIMARY KEY,
    CUSTOMER_ID INTEGER,
    EVENT_TYPE VARCHAR(50) NOT NULL,
    EVENT_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    EVENT_DATA VARCHAR(2000),
    SESSION_ID VARCHAR(100),
    IP_ADDRESS VARCHAR(45),
    USER_AGENT VARCHAR(500),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_EVENTS_CUSTOMER ON CUSTOMER_EVENTS(CUSTOMER_ID);
CREATE INDEX IDX_EVENTS_TYPE ON CUSTOMER_EVENTS(EVENT_TYPE);
CREATE INDEX IDX_EVENTS_TIMESTAMP ON CUSTOMER_EVENTS(EVENT_TIMESTAMP);

COMMENT ON TABLE CUSTOMER_EVENTS IS 'Customer event stream - test table for high-volume inserts';

-- ============================================================================
-- DATA_QUALITY_TEST Table - For testing NULL handling and data types
-- ============================================================================
CREATE TABLE DATA_QUALITY_TEST (
    ID INTEGER NOT NULL PRIMARY KEY,
    REQUIRED_TEXT VARCHAR(100) NOT NULL,
    OPTIONAL_TEXT VARCHAR(100),
    REQUIRED_NUMBER INTEGER NOT NULL,
    OPTIONAL_NUMBER DECIMAL(10, 2),
    REQUIRED_DATE DATE NOT NULL,
    OPTIONAL_DATE DATE,
    REQUIRED_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    OPTIONAL_TIMESTAMP TIMESTAMP,
    BOOLEAN_FLAG SMALLINT DEFAULT 0,
    LARGE_TEXT CLOB,
    BINARY_DATA BLOB,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE DATA_QUALITY_TEST IS 'Data quality validation - test table for NULL handling and type conversion';

-- ============================================================================
-- CUSTOMER_FEED_CURATED Table - For Oracle demo workflow replace loads
-- ============================================================================
CREATE TABLE CUSTOMER_FEED_CURATED (
    STAGE_ROW_ID VARCHAR(20) NOT NULL,
    CUSTOMER_CODE VARCHAR(20) NOT NULL,
    FULL_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(120) NOT NULL,
    SEGMENT VARCHAR(20),
    STATUS VARCHAR(20),
    COUNTRY_CODE VARCHAR(10),
    LIFETIME_VALUE DECIMAL(12, 2),
    UPDATED_AT TIMESTAMP NOT NULL,
    PRIMARY KEY (STAGE_ROW_ID)
);

CREATE INDEX IDX_CUSTOMER_FEED_CURATED_EMAIL ON CUSTOMER_FEED_CURATED(EMAIL);
CREATE INDEX IDX_CUSTOMER_FEED_CURATED_CODE ON CUSTOMER_FEED_CURATED(CUSTOMER_CODE);

COMMENT ON TABLE CUSTOMER_FEED_CURATED IS 'Curated Oracle demo customer feed loaded by the workflow demo stack';
COMMENT ON COLUMN CUSTOMER_FEED_CURATED.STAGE_ROW_ID IS 'Original Oracle staging row identifier kept for traceability';
COMMENT ON COLUMN CUSTOMER_FEED_CURATED.EMAIL IS 'Normalized email used for exact deduplication in the demo workflow';

-- ============================================================================
-- Initial test data
-- ============================================================================

-- Sample customers for MERGE testing
INSERT INTO CUSTOMERS (CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, DATE_OF_BIRTH, LOYALTY_POINTS, CUSTOMER_SEGMENT) VALUES
(1, 'Alice', 'Anderson', 'alice@example.com', '555-0101', '1985-03-15', 1500, 'GOLD'),
(2, 'Bob', 'Brown', 'bob@example.com', '555-0102', '1990-07-22', 800, 'SILVER'),
(3, 'Charlie', 'Chen', 'charlie@example.com', '555-0103', '1988-11-30', 250, 'BRONZE');

-- Sample products for composite key MERGE testing
INSERT INTO PRODUCTS (PRODUCT_ID, VARIANT_ID, PRODUCT_NAME, CATEGORY, SUBCATEGORY, UNIT_PRICE, COST_PRICE, IN_STOCK) VALUES
(100, 1, 'Classic T-Shirt - Blue Small', 'Apparel', 'T-Shirts', 19.99, 8.50, 150),
(100, 2, 'Classic T-Shirt - Blue Medium', 'Apparel', 'T-Shirts', 19.99, 8.50, 200),
(100, 3, 'Classic T-Shirt - Blue Large', 'Apparel', 'T-Shirts', 19.99, 8.50, 180),
(101, 1, 'Premium Jeans - Black 32x32', 'Apparel', 'Jeans', 59.99, 25.00, 75);

-- Sample orders for INSERT testing
INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_STATUS, SUBTOTAL, TAX_AMOUNT, TOTAL_AMOUNT) VALUES
(1001, 1, 'COMPLETED', 100.00, 8.00, 108.00),
(1002, 2, 'COMPLETED', 59.99, 4.80, 64.79),
(1003, 3, 'PENDING', 39.98, 3.20, 43.18);

-- Sample order items
INSERT INTO ORDER_ITEMS (ORDER_ITEM_ID, ORDER_ID, PRODUCT_ID, VARIANT_ID, QUANTITY, UNIT_PRICE, LINE_TOTAL) VALUES
(10001, 1001, 100, 1, 2, 19.99, 39.98),
(10002, 1001, 101, 1, 1, 59.99, 59.99),
(10003, 1002, 101, 1, 1, 59.99, 59.99),
(10004, 1003, 100, 2, 2, 19.99, 39.98);

-- Create reorg table for better performance
REORG TABLE CUSTOMERS;
REORG TABLE PRODUCTS;
REORG TABLE ORDERS;
REORG TABLE ORDER_ITEMS;
REORG TABLE CUSTOMER_EVENTS;
REORG TABLE DATA_QUALITY_TEST;
REORG TABLE CUSTOMER_FEED_CURATED;

-- Update statistics for query optimizer
RUNSTATS ON TABLE CUSTOMERS WITH DISTRIBUTION AND DETAILED INDEXES ALL;
RUNSTATS ON TABLE PRODUCTS WITH DISTRIBUTION AND DETAILED INDEXES ALL;
RUNSTATS ON TABLE ORDERS WITH DISTRIBUTION AND DETAILED INDEXES ALL;
RUNSTATS ON TABLE ORDER_ITEMS WITH DISTRIBUTION AND DETAILED INDEXES ALL;
RUNSTATS ON TABLE CUSTOMER_EVENTS WITH DISTRIBUTION AND DETAILED INDEXES ALL;
RUNSTATS ON TABLE DATA_QUALITY_TEST WITH DISTRIBUTION AND DETAILED INDEXES ALL;
RUNSTATS ON TABLE CUSTOMER_FEED_CURATED WITH DISTRIBUTION AND DETAILED INDEXES ALL;

COMMIT WORK;

CONNECT RESET;
