ALTER SESSION SET CONTAINER = FREEPDB1;

CREATE TABLE ARCXA_DEMO.CUSTOMERS (
    CUSTOMER_ID VARCHAR2(20) PRIMARY KEY,
    FULL_NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(120) NOT NULL,
    SEGMENT VARCHAR2(20),
    LIFETIME_VALUE NUMBER(10, 2),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

INSERT INTO ARCXA_DEMO.CUSTOMERS (CUSTOMER_ID, FULL_NAME, EMAIL, SEGMENT, LIFETIME_VALUE, UPDATED_AT)
VALUES ('CUST001', 'Alice Example', 'alice@example.com', 'gold', 1250.50, TIMESTAMP '2026-03-01 10:00:00');

INSERT INTO ARCXA_DEMO.CUSTOMERS (CUSTOMER_ID, FULL_NAME, EMAIL, SEGMENT, LIFETIME_VALUE, UPDATED_AT)
VALUES ('CUST002', 'Bob Example', 'bob@example.com', 'silver', 850.00, TIMESTAMP '2026-03-02 11:30:00');

INSERT INTO ARCXA_DEMO.CUSTOMERS (CUSTOMER_ID, FULL_NAME, EMAIL, SEGMENT, LIFETIME_VALUE, UPDATED_AT)
VALUES ('CUST003', 'Carol Example', 'carol@example.com', 'bronze', 420.75, TIMESTAMP '2026-03-03 09:15:00');

CREATE TABLE ARCXA_DEMO.CUSTOMER_FEED (
    STAGE_ROW_ID VARCHAR2(20) PRIMARY KEY,
    CUSTOMER_CODE VARCHAR2(20) NOT NULL,
    FULL_NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(120) NOT NULL,
    SEGMENT VARCHAR2(20),
    STATUS VARCHAR2(20),
    COUNTRY_CODE VARCHAR2(10),
    LIFETIME_VALUE NUMBER(12, 3),
    UPDATED_AT TIMESTAMP NOT NULL
);

INSERT INTO ARCXA_DEMO.CUSTOMER_FEED (
    STAGE_ROW_ID,
    CUSTOMER_CODE,
    FULL_NAME,
    EMAIL,
    SEGMENT,
    STATUS,
    COUNTRY_CODE,
    LIFETIME_VALUE,
    UPDATED_AT
)
VALUES (
    'FEED001',
    'CUST001',
    '  Alice Example  ',
    ' Alice@example.com ',
    ' Gold ',
    'active',
    'us',
    1250.555,
    TIMESTAMP '2026-03-10 08:00:00'
);

INSERT INTO ARCXA_DEMO.CUSTOMER_FEED (
    STAGE_ROW_ID,
    CUSTOMER_CODE,
    FULL_NAME,
    EMAIL,
    SEGMENT,
    STATUS,
    COUNTRY_CODE,
    LIFETIME_VALUE,
    UPDATED_AT
)
VALUES (
    'FEED002',
    'CUST001_DUP',
    'Alice Example',
    'ALICE@EXAMPLE.COM',
    'Gold',
    'ACTIVE',
    'us',
    1300.100,
    TIMESTAMP '2026-03-10 08:05:00'
);

INSERT INTO ARCXA_DEMO.CUSTOMER_FEED (
    STAGE_ROW_ID,
    CUSTOMER_CODE,
    FULL_NAME,
    EMAIL,
    SEGMENT,
    STATUS,
    COUNTRY_CODE,
    LIFETIME_VALUE,
    UPDATED_AT
)
VALUES (
    'FEED003',
    'CUST002',
    'Bob Example',
    'bob@example.com',
    'Silver',
    'inactive',
    'ca',
    850.000,
    TIMESTAMP '2026-03-11 09:15:00'
);

INSERT INTO ARCXA_DEMO.CUSTOMER_FEED (
    STAGE_ROW_ID,
    CUSTOMER_CODE,
    FULL_NAME,
    EMAIL,
    SEGMENT,
    STATUS,
    COUNTRY_CODE,
    LIFETIME_VALUE,
    UPDATED_AT
)
VALUES (
    'FEED004',
    'CUST003',
    'Carol Example',
    'carol@example.com',
    'Bronze',
    NULL,
    'USA',
    420.754,
    TIMESTAMP '2026-03-11 09:45:00'
);

INSERT INTO ARCXA_DEMO.CUSTOMER_FEED (
    STAGE_ROW_ID,
    CUSTOMER_CODE,
    FULL_NAME,
    EMAIL,
    SEGMENT,
    STATUS,
    COUNTRY_CODE,
    LIFETIME_VALUE,
    UPDATED_AT
)
VALUES (
    'FEED005',
    'CUST004',
    'Dan Example ',
    'dan@example.com',
    ' Gold',
    'active',
    'gb',
    2200.499,
    TIMESTAMP '2026-03-12 10:30:00'
);

INSERT INTO ARCXA_DEMO.CUSTOMER_FEED (
    STAGE_ROW_ID,
    CUSTOMER_CODE,
    FULL_NAME,
    EMAIL,
    SEGMENT,
    STATUS,
    COUNTRY_CODE,
    LIFETIME_VALUE,
    UPDATED_AT
)
VALUES (
    'FEED006',
    'CUST005',
    'Eve Example',
    'eve@example.com',
    'Silver',
    'active',
    'de',
    998.888,
    TIMESTAMP '2026-03-12 12:00:00'
);

CREATE TABLE ARCXA_DEMO.CUSTOMER_DIM (
    STAGE_ROW_ID VARCHAR2(20),
    CUSTOMER_CODE VARCHAR2(20) PRIMARY KEY,
    FULL_NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(120) NOT NULL,
    SEGMENT VARCHAR2(20),
    STATUS VARCHAR2(20),
    COUNTRY_CODE VARCHAR2(10),
    LIFETIME_VALUE NUMBER(12, 2),
    UPDATED_AT TIMESTAMP NOT NULL
);

COMMIT;
