ALTER SESSION SET CONTAINER = FREEPDB1;

CREATE TABLE ARCXA_DEMO.CUSTOMERS (
    CUSTOMER_ID VARCHAR2(20) PRIMARY KEY,
    FULL_NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(120) NOT NULL,
    SEGMENT VARCHAR2(20),
    LIFETIME_VALUE NUMBER(10, 2),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

INSERT INTO ARCXA_DEMO.CUSTOMERS (CUSTOMER_ID, FULL_NAME, EMAIL, SEGMENT, LIFETIME_VALUE, UPDATED_AT)
VALUES ('CUST001', 'Alice Example', 'alice@example.com', 'gold', 1250.50, TIMESTAMP '2026-03-01 10:00:00');

INSERT INTO ARCXA_DEMO.CUSTOMERS (CUSTOMER_ID, FULL_NAME, EMAIL, SEGMENT, LIFETIME_VALUE, UPDATED_AT)
VALUES ('CUST002', 'Bob Example', 'bob@example.com', 'silver', 850.00, TIMESTAMP '2026-03-02 11:30:00');

INSERT INTO ARCXA_DEMO.CUSTOMERS (CUSTOMER_ID, FULL_NAME, EMAIL, SEGMENT, LIFETIME_VALUE, UPDATED_AT)
VALUES ('CUST003', 'Carol Example', 'carol@example.com', 'bronze', 420.75, TIMESTAMP '2026-03-03 09:15:00');

INSERT INTO ARCXA_DEMO.CUSTOMERS (CUSTOMER_ID, FULL_NAME, EMAIL, SEGMENT, LIFETIME_VALUE, UPDATED_AT)
VALUES ('CUST004', 'Dan Example', 'dan@example.com', 'gold', 2200.49, TIMESTAMP '2026-03-04 14:20:00');

INSERT INTO ARCXA_DEMO.CUSTOMERS (CUSTOMER_ID, FULL_NAME, EMAIL, SEGMENT, LIFETIME_VALUE, UPDATED_AT)
VALUES ('CUST005', 'Eve Example', 'eve@example.com', 'silver', 998.88, TIMESTAMP '2026-03-05 16:45:00');

CREATE TABLE ARCXA_DEMO.CUSTOMER_FEED (
    STAGE_ROW_ID VARCHAR2(20) PRIMARY KEY,
    CUSTOMER_CODE VARCHAR2(20) NOT NULL,
    FULL_NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(120) NOT NULL,
    SEGMENT VARCHAR2(20),
    STATUS VARCHAR2(20),
    COUNTRY_CODE VARCHAR2(10),
    LIFETIME_VALUE NUMBER(12, 3),
    UPDATED_AT TIMESTAMP NOT NULL
);

INSERT INTO ARCXA_DEMO.CUSTOMER_FEED (
    STAGE_ROW_ID,
    CUSTOMER_CODE,
    FULL_NAME,
    EMAIL,
    SEGMENT,
    STATUS,
    COUNTRY_CODE,
    LIFETIME_VALUE,
    UPDATED_AT
)
VALUES (
    'FEED001',
    'CUST001',
    '  Alice Example  ',
    ' Alice@example.com ',
    ' Gold ',
    'active',
    'us',
    1250.555,
    TIMESTAMP '2026-03-10 08:00:00'
);

INSERT INTO ARCXA_DEMO.CUSTOMER_FEED (
    STAGE_ROW_ID,
    CUSTOMER_CODE,
    FULL_NAME,
    EMAIL,
    SEGMENT,
    STATUS,
    COUNTRY_CODE,
    LIFETIME_VALUE,
    UPDATED_AT
)
VALUES (
    'FEED002',
    'CUST001_DUP',
    'Alice Example',
    'ALICE@EXAMPLE.COM',
    'Gold',
    'ACTIVE',
    'us',
    1300.100,
    TIMESTAMP '2026-03-10 08:05:00'
);

INSERT INTO ARCXA_DEMO.CUSTOMER_FEED (
    STAGE_ROW_ID,
    CUSTOMER_CODE,
    FULL_NAME,
    EMAIL,
    SEGMENT,
    STATUS,
    COUNTRY_CODE,
    LIFETIME_VALUE,
    UPDATED_AT
)
VALUES (
    'FEED003',
    'CUST002',
    'Bob Example',
    'bob@example.com',
    'Silver',
    'inactive',
    'ca',
    850.000,
    TIMESTAMP '2026-03-11 09:15:00'
);

INSERT INTO ARCXA_DEMO.CUSTOMER_FEED (
    STAGE_ROW_ID,
    CUSTOMER_CODE,
    FULL_NAME,
    EMAIL,
    SEGMENT,
    STATUS,
    COUNTRY_CODE,
    LIFETIME_VALUE,
    UPDATED_AT
)
VALUES (
    'FEED004',
    'CUST003',
    'Carol Example',
    'carol@example.com',
    'Bronze',
    NULL,
    'USA',
    420.754,
    TIMESTAMP '2026-03-11 09:45:00'
);

INSERT INTO ARCXA_DEMO.CUSTOMER_FEED (
    STAGE_ROW_ID,
    CUSTOMER_CODE,
    FULL_NAME,
    EMAIL,
    SEGMENT,
    STATUS,
    COUNTRY_CODE,
    LIFETIME_VALUE,
    UPDATED_AT
)
VALUES (
    'FEED005',
    'CUST004',
    'Dan Example ',
    'dan@example.com',
    ' Gold',
    'active',
    'gb',
    2200.499,
    TIMESTAMP '2026-03-12 10:30:00'
);

INSERT INTO ARCXA_DEMO.CUSTOMER_FEED (
    STAGE_ROW_ID,
    CUSTOMER_CODE,
    FULL_NAME,
    EMAIL,
    SEGMENT,
    STATUS,
    COUNTRY_CODE,
    LIFETIME_VALUE,
    UPDATED_AT
)
VALUES (
    'FEED006',
    'CUST005',
    'Eve Example',
    'eve@example.com',
    'Silver',
    'active',
    'de',
    998.888,
    TIMESTAMP '2026-03-12 12:00:00'
);

CREATE TABLE ARCXA_DEMO.CUSTOMER_DIM (
    STAGE_ROW_ID VARCHAR2(20),
    CUSTOMER_CODE VARCHAR2(20) PRIMARY KEY,
    FULL_NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(120) NOT NULL,
    SEGMENT VARCHAR2(20),
    STATUS VARCHAR2(20),
    COUNTRY_CODE VARCHAR2(10),
    LIFETIME_VALUE NUMBER(12, 2),
    UPDATED_AT TIMESTAMP NOT NULL
);

CREATE TABLE ARCXA_DEMO.CUSTOMER_ORDERS (
    ORDER_ID VARCHAR2(20) PRIMARY KEY,
    CUSTOMER_ID VARCHAR2(20) NOT NULL,
    ORDER_TOTAL NUMBER(12, 2) NOT NULL,
    ORDER_STATUS VARCHAR2(20) NOT NULL,
    ORDER_CHANNEL VARCHAR2(20),
    ORDERED_AT TIMESTAMP NOT NULL,
    CONSTRAINT FK_CUSTOMER_ORDERS_CUSTOMER
        FOREIGN KEY (CUSTOMER_ID) REFERENCES ARCXA_DEMO.CUSTOMERS (CUSTOMER_ID)
);

INSERT INTO ARCXA_DEMO.CUSTOMER_ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_TOTAL, ORDER_STATUS, ORDER_CHANNEL, ORDERED_AT)
VALUES ('ORD001', 'CUST001', 249.99, 'fulfilled', 'web', TIMESTAMP '2026-03-06 10:00:00');

INSERT INTO ARCXA_DEMO.CUSTOMER_ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_TOTAL, ORDER_STATUS, ORDER_CHANNEL, ORDERED_AT)
VALUES ('ORD002', 'CUST001', 89.50, 'fulfilled', 'mobile', TIMESTAMP '2026-03-08 18:15:00');

INSERT INTO ARCXA_DEMO.CUSTOMER_ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_TOTAL, ORDER_STATUS, ORDER_CHANNEL, ORDERED_AT)
VALUES ('ORD003', 'CUST002', 420.00, 'fulfilled', 'web', TIMESTAMP '2026-03-09 08:45:00');

INSERT INTO ARCXA_DEMO.CUSTOMER_ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_TOTAL, ORDER_STATUS, ORDER_CHANNEL, ORDERED_AT)
VALUES ('ORD004', 'CUST002', 55.25, 'returned', 'partner', TIMESTAMP '2026-03-12 11:10:00');

INSERT INTO ARCXA_DEMO.CUSTOMER_ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_TOTAL, ORDER_STATUS, ORDER_CHANNEL, ORDERED_AT)
VALUES ('ORD005', 'CUST003', 120.00, 'fulfilled', 'store', TIMESTAMP '2026-03-12 15:40:00');

INSERT INTO ARCXA_DEMO.CUSTOMER_ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_TOTAL, ORDER_STATUS, ORDER_CHANNEL, ORDERED_AT)
VALUES ('ORD006', 'CUST004', 760.00, 'fulfilled', 'enterprise', TIMESTAMP '2026-03-13 09:30:00');

INSERT INTO ARCXA_DEMO.CUSTOMER_ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_TOTAL, ORDER_STATUS, ORDER_CHANNEL, ORDERED_AT)
VALUES ('ORD007', 'CUST004', 1440.49, 'pending', 'web', TIMESTAMP '2026-03-15 13:20:00');

INSERT INTO ARCXA_DEMO.CUSTOMER_ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_TOTAL, ORDER_STATUS, ORDER_CHANNEL, ORDERED_AT)
VALUES ('ORD008', 'CUST005', 305.10, 'fulfilled', 'mobile', TIMESTAMP '2026-03-16 17:05:00');

CREATE OR REPLACE VIEW ARCXA_DEMO.CUSTOMER_360 AS
SELECT
    c.CUSTOMER_ID,
    c.FULL_NAME,
    c.EMAIL,
    c.SEGMENT,
    c.LIFETIME_VALUE,
    NVL(order_summary.ORDER_COUNT, 0) AS ORDER_COUNT,
    order_summary.LAST_ORDER_STATUS,
    order_summary.LAST_ORDER_TOTAL,
    order_summary.LAST_ORDER_AT
FROM ARCXA_DEMO.CUSTOMERS c
LEFT JOIN (
    SELECT
        customer_id,
        COUNT(*) AS ORDER_COUNT,
        MAX(order_status) KEEP (DENSE_RANK LAST ORDER BY ordered_at) AS LAST_ORDER_STATUS,
        MAX(order_total) KEEP (DENSE_RANK LAST ORDER BY ordered_at) AS LAST_ORDER_TOTAL,
        MAX(ordered_at) AS LAST_ORDER_AT
    FROM ARCXA_DEMO.CUSTOMER_ORDERS
    GROUP BY customer_id
) order_summary
    ON order_summary.customer_id = c.CUSTOMER_ID;

COMMIT;
